### ISSUE TITLE
TypeError: this.sub is null

### ISSUE THREAD

**Issue by jethrogb** [lapo-luchini/asn1js#15]
When trying to decode:

```
045601036b6579044d00000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000001100
```

With `openssl asn1parse`:

```
    0:d=0  hl=2 l=  86 prim: OCTET STRING      [HEX DUMP]:01036B6579044D0000...001100
```

**Comment by lapo-luchini** [comment]
It seems to be encapsulating valid content (as in: it can be correctly parsed) but fails on display because a `SET` with no content wasn't expected.

**Comment by jethrogb** [comment]
Great, thanks! The content might have looked like valid ASN.1 but in this case it was some other blob.

**Comment by lapo-luchini** [comment]
Yeah, I assumed as much, but just like dumpasn1 C software this is inspired
to, it tries to show encapsulated structures if they parse correctly; this
was good enough to parse, but unexpected enough not to render in the DOM.

Il giorno dom 17 gen 2016 22:36 jethrogb <notifications@github.com> ha
scritto:
