### ISSUE TITLE
link to asn1.js does not work in Firefox with spaces in the Certificate

### ISSUE THREAD

**Issue by rubo77** [lapo-luchini/asn1js#16]
When folowing [this link](http://lapo.it/asn1js/#-----BEGIN%20CERTIFICATE-----MIIE/zCCAuegAwIBAgIDDPb5MA0GCSqGSIb3DQEBBQUAMHkxEDAOBgNVBAoTB1Jvb3QgQ0ExHjAcBgNVBAsTFWh0dHA6Ly93d3cuY2FjZXJ0Lm9yZzEiMCAGA1UEAxMZQ0EgQ2VydCBTaWduaW5nIEF1dGhvcml0eTEhMB8GCSqGSIb3DQEJARYSc3VwcG9ydEBjYWNlcnQub3JnMB4XDTEzMDMxMTIwMDMzOVoXDTE1MDMxMTIwMDMzOVowFjEUMBIGA1UEAxQLKi5lY2xhYnMuZGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDmLl/nGWD8vUfv143Q4Zyq6zTViTagALX8SqwqVe0aSUgWDecxirtWxqI9kmFqTfvIhfjD8C+ZAmAAx2c9nlIHy9MiASBn4SaWhrc8Hc5eRhpokDVmaaXgLizaZVQJN65jFfBVdPffhHqJXHOqfkdkFp8fCv9mDiPacZnBhhgkR/lxxQ1B2m6u0x0wiFwpqaDI6KS4/++7rDkor9CyQrzChvffZYipECEB1W1v6BlxwAqKoXLa3+Cyk8FJILjlPnRNOnOuf5hKZjPFKRqvXBkBA4BqO39p25rH9ou1h5CdyviqtXiBFZLrPsaF0nybV6H5gniP52w7K7Ot07QNEwOhAgMBAAGjgfIwge8wDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCA6gwNAYDVR0lBC0wKwYIKwYBBQUHAwIGCCsGAQUFBwMBBglghkgBhvhCBAEGCisGAQQBgjcKAwMwMwYIKwYBBQUHAQEEJzAlMCMGCCsGAQUFBzABhhdodHRwOi8vb2NzcC5jYWNlcnQub3JnLzAxBgNVHR8EKjAoMCagJKAihiBodHRwOi8vY3JsLmNhY2VydC5vcmcvcmV2b2tlLmNybDAxBgNVHREEKjAoggsqLmVjbGFicy5kZaAZBggrBgEFBQcIBaANDAsqLmVjbGFicy5kZTANBgkqhkiG9w0BAQUFAAOCAgEABk0x589FLbPcOIHFK2hlhUz0Wt6aAadPgqumEvvZFLm4lp0ndS43JkP+o9Ek4kk8YauEBbaj8q8hYMQN3CF6JQVKnpf8piIxQk9qiCHJPR74eItUjASxE0SNqgOKhIi5Z5/q0t1oPdgAsVdEMAbp8wlKSeFZvjBMPZaNVb6P1KxnaDTLE0gUaEsoKiU8yimPqamL44AQgt5UZZrXl1BYeiG2UGmAPezlOihSBv+Hj4Z8FNhhA/VJr9imXiseFQNvMZQQ4Mwf5CVw66QnUgh4gFyPczOY+FSyRGBrGYYjPSUNItpHEOk1A21koBJvRu/xVrYacmQ08oYkwLLbUTBiaw5fl91mVTZ3eqHQdBncxBWrDJFFI24yyd8mwkUlRvQICc2rEbh734jFVtqpZ+kFd8Ux6a1tbGIbocSexNGM5pCy+HtRH0H2emkTn0dkctJM9O4chXdCtwEH0igtuB2p59tgPhDi1LtLW+f9HP21ULQYNoqGUZGr5aqCg2ftA0ogyjEbYRfDU7DSok249vHLGuL1BNNNPOjmzVihWIfbKzqunu1pWH7ykASZBzSGgRJQy5JqME7eGcn+EJBipOrby4LPAmk3a/MyARvGnJ5moe/4JdU7x41tPuPSZ93zD6x4KGRO7bZbBwDAGW7OcKyc7XZrp7vH43PgdoTsXqe1tpY=-----END%20CERTIFICATE-----) (containing `%20`) the script does not work in Firefox.

If I replace the `%20` with `+` [it doesn't work either](http://lapo.it/asn1js/#-----BEGIN+CERTIFICATE-----MIIE/zCCAuegAwIBAgIDDPb5MA0GCSqGSIb3DQEBBQUAMHkxEDAOBgNVBAoTB1Jvb3QgQ0ExHjAcBgNVBAsTFWh0dHA6Ly93d3cuY2FjZXJ0Lm9yZzEiMCAGA1UEAxMZQ0EgQ2VydCBTaWduaW5nIEF1dGhvcml0eTEhMB8GCSqGSIb3DQEJARYSc3VwcG9ydEBjYWNlcnQub3JnMB4XDTEzMDMxMTIwMDMzOVoXDTE1MDMxMTIwMDMzOVowFjEUMBIGA1UEAxQLKi5lY2xhYnMuZGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDmLl/nGWD8vUfv143Q4Zyq6zTViTagALX8SqwqVe0aSUgWDecxirtWxqI9kmFqTfvIhfjD8C+ZAmAAx2c9nlIHy9MiASBn4SaWhrc8Hc5eRhpokDVmaaXgLizaZVQJN65jFfBVdPffhHqJXHOqfkdkFp8fCv9mDiPacZnBhhgkR/lxxQ1B2m6u0x0wiFwpqaDI6KS4/++7rDkor9CyQrzChvffZYipECEB1W1v6BlxwAqKoXLa3+Cyk8FJILjlPnRNOnOuf5hKZjPFKRqvXBkBA4BqO39p25rH9ou1h5CdyviqtXiBFZLrPsaF0nybV6H5gniP52w7K7Ot07QNEwOhAgMBAAGjgfIwge8wDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCA6gwNAYDVR0lBC0wKwYIKwYBBQUHAwIGCCsGAQUFBwMBBglghkgBhvhCBAEGCisGAQQBgjcKAwMwMwYIKwYBBQUHAQEEJzAlMCMGCCsGAQUFBzABhhdodHRwOi8vb2NzcC5jYWNlcnQub3JnLzAxBgNVHR8EKjAoMCagJKAihiBodHRwOi8vY3JsLmNhY2VydC5vcmcvcmV2b2tlLmNybDAxBgNVHREEKjAoggsqLmVjbGFicy5kZaAZBggrBgEFBQcIBaANDAsqLmVjbGFicy5kZTANBgkqhkiG9w0BAQUFAAOCAgEABk0x589FLbPcOIHFK2hlhUz0Wt6aAadPgqumEvvZFLm4lp0ndS43JkP+o9Ek4kk8YauEBbaj8q8hYMQN3CF6JQVKnpf8piIxQk9qiCHJPR74eItUjASxE0SNqgOKhIi5Z5/q0t1oPdgAsVdEMAbp8wlKSeFZvjBMPZaNVb6P1KxnaDTLE0gUaEsoKiU8yimPqamL44AQgt5UZZrXl1BYeiG2UGmAPezlOihSBv+Hj4Z8FNhhA/VJr9imXiseFQNvMZQQ4Mwf5CVw66QnUgh4gFyPczOY+FSyRGBrGYYjPSUNItpHEOk1A21koBJvRu/xVrYacmQ08oYkwLLbUTBiaw5fl91mVTZ3eqHQdBncxBWrDJFFI24yyd8mwkUlRvQICc2rEbh734jFVtqpZ+kFd8Ux6a1tbGIbocSexNGM5pCy+HtRH0H2emkTn0dkctJM9O4chXdCtwEH0igtuB2p59tgPhDi1LtLW+f9HP21ULQYNoqGUZGr5aqCg2ftA0ogyjEbYRfDU7DSok249vHLGuL1BNNNPOjmzVihWIfbKzqunu1pWH7ykASZBzSGgRJQy5JqME7eGcn+EJBipOrby4LPAmk3a/MyARvGnJ5moe/4JdU7x41tPuPSZ93zD6x4KGRO7bZbBwDAGW7OcKyc7XZrp7vH43PgdoTsXqe1tpY=-----END+CERTIFICATE-----)

The only solution seems to be replacing the `%20` in the textbox on the resulting page with a space.

**Comment by lapo-luchini** [comment]
[RFC 2396](http://www.ietf.org/rfc/rfc2396.txt) section 4.1 states that the fragment is not part of the URI but is subject to the same character restrictions apply, so I would guess with that that browsers would decode that %20 just as it was part of the URI… but Chrome doesn't, while SeaMonkey do (strange, as you quote Firefox as not doing it, and should be the same as SeaMonkey).

I tested four links:

1. your link with %20
2. your linkwith +
3. a link with a bare space
4. bare base64 without PEM headers

And the following is working OK:

* Chrome 47: `3, 4.`
* SeaMonkey 2.33.1: `1, 3, 4.`
* Internet Explorer 11: `3, 4.`
* Microsoft Edge: `3, 4.`
* Konqueror: `4.` (!!!)

So it seems that major browsers just want fragments with bare spaces, or you can just avoid the PEM headers and use the bare base64 (or hex) content, which doesn't have spaces at all and avoid the problem altogether.

Anyways, I'd say it's not a bug of this software how the browser decides to decode the fragment part of the URI, as it simply reads it with `window.location.hash`. (feel free to re-open the bug if you disagree)

**Comment by rubo77** [comment]
I cannot reopen the bug, but why didn't you test in firefox 43?
I think there is missing something like a `urldecode` or you could simply add an `if contains "%20" .. replace with space` in your code so it woud work in firefox too

**Comment by lapo-luchini** [comment]
It's not my fault if [Firefox has had unresolved bugs known since 2002](https://bugzilla.mozilla.org/show_bug.cgi?id=135309) and while other libraries such as [YUI do have specific work-arounds](http://yuilibrary.com/yui/docs/api/files/history_js_history-hash.js.html#l206) I'm not really OK with that browser-specific approach.

On the other hand decoding the fragment is the correct think to do in any case (and this fixes the link in Chrome too); in bugged versions of Firefox this leads to risk of double-decoding, but since e real `%` value is not a valid in either base64 nor hexadecimal encoding, the eventual double-decoding would not be an issue.

Please notice that the feature this bug is about is *undocumented* and at least partially unintended: the software itself only uses hexadecimal encoding in the hash, for the very reason that it restricts values to a very safe subset which needs no special encoding nor decoding.
