### ISSUE TITLE
What is the fastest way to locate a specific OID?

### ISSUE THREAD

**Issue by totszwai** [lapo-luchini/asn1js#18]
I'm trying to use this to locate the 1.2.840.113549.1.1.1 (RSA encryption hash)... If I only use the asn1.js, what is the best way to find the OID?

I don't think going in and comparing the hexDump or parseOctetString is the way to go...?

parsed.sub[0].stream.hexDump(4,15)
"06 09 2A 86  48 86 F7 0D 01 07 02 "
parsed.sub[0].stream.parseOctetString(4,15)
"(11 byte)
06092A864886F70D010702"

**Comment by lapo-luchini** [comment]
What do you mean by "locating" the OID?
If you mean if you an unknown tree and need to find the node which is that OID, I guess you could you something recursive like this:

    var r = function(e) {
        if (e.typeName() == 'OBJECT_IDENTIFIER')
            console.log(e.content());
        if (e.sub) e.sub.forEach(r);
    };
    r(parsed);

**Comment by totszwai** [comment]
I am using something like this right now, but

```
	var s = node.stream;
	var start = s.pos + node.header;
	var stop = start + node.length;
	...
	switch(node.tag.tagNumber) {
		case 0x06: // OBJECT_IDENTIFIER 
		{
			var hex = s.hexDump(start, stop, true);
			console.log("OBJECT_IDENTIFIER :" + hex);
			if (hex == "2A864886F70D010101")
			{
				console.log("Found");
				found = true;
			}
		}
```

Which is kind a ugly, I was trying to use parseOID to get the actual OID and compare it directly that way, but it keeps saying parseOID doesn't exists (when is clearly there!)..

**Comment by lapo-luchini** [comment]
As in my example above, you probably better use the node logic that is already there (`e.typeName()` and `e.content()`) instead of re-implementing using the stream and the tag numbers directly.

Example fiddle: https://jsfiddle.net/lapo/o4dw21da/1/

BTW: I'm closing this as not being a bug but a discussion, but feel free to reply further.
