### ISSUE TITLE
HEX parsing problem

### ISSUE THREAD

**Issue by microshine** [lapo-luchini/asn1js#20]
I'm trying to decode HEX string via your Web application
```
30820122300D06092A864886F70D01010105000382010F003082010A0282010100B77D41B8B39F2CD2881F44E22878E1D5F621D8D591F73B790AA61BFB7B0E8C2CE4F
43A8C6F5D97273DE644E86D1C24E6F01F129C31D97DBD4238D3DDE218BF1FEB59C26A1571F46325D47964DA5EB7ADDC9D32DF3402A1DF5F0921A52E51B8CA4A8FA139
F17136065270A7B5BBA155A4DBB871D79768C90445D25FBA72A76FD690625914F18E9411538B8EF97736B387EC36B83E3689F935C45F64D56B5A794F3764C017815DD
C6A85AA1FDE6371D05C2196CA6771A7D836CEB534609B312EF58E25846BA9B028C7E246BF0965543837C8A30447D2D985F704B5B05A36C851570BDC91E21930405D82
BE0847CE4F1020B28F5C6F72CFE61D5D2C6A90435ED9F10203010001
```
My HEX string has new lines. When I click on Decode button I've got wrong decoded message

![image](https://cloud.githubusercontent.com/assets/7333669/26344632/01e7d5e2-3fa9-11e7-92b1-a7e6656481a3.png)

but must be

![image](https://cloud.githubusercontent.com/assets/7333669/26344666/1a97bc06-3fa9-11e7-8685-18c7b578a15e.png)

**Comment by Adapik** [comment]
String must be base64-encoded, not in hex format

**Comment by microshine** [comment]
As you can see it can work with HEX string too. It's very useful, because sometimes it's easier to receive HEX from application than BASE64

**Comment by luis140219** [comment]
Hex strings with an odd number of hex characters fail hex decoding and pass to Base64 decoding.

**Comment by lapo-luchini** [comment]
Yes, newlines are OK, but only on byte boundaries.
Actually the decoded would probably accept it, it's the "sanity check" done via `reHex` regular expression that chokes on it.

**Comment by lapo-luchini** [comment]
I don't think spaces in the middle of a byte is a very common hex format usage, so I'd close this bug with no change regarding that.
