### ISSUE TITLE
Not handling fractional seconds properly

### ISSUE THREAD

**Issue by ghost** [lapo-luchini/asn1js#22]
When I put a time with fractional seconds in a GeneralizedTime, asn1js says "Unrecognized time".

**Comment by lapo-luchini** [comment]
Can you give an example value?
`181332303138303832333033313032302E3435365A ` seems to be correctly decoded to `2018-08-23 03:10:20.456 UTC`.
Is it following the [proper format](https://www.obj-sys.com/asn1tutorial/node14.html)?

**Comment by lapo-luchini** [comment]
Closing for timeout, feel free to re-open with more data and possibly an example value to reproduce the problem.
