### ISSUE TITLE
Boolean inside boolean

### ISSUE THREAD

**Issue by phadej** [lapo-luchini/asn1js#23]
when I try to decode data
```
21060101ff0101ff
```
https://lapo.it/asn1js/#21060101FF010100

The interesting:

- BOOLEAN true
    - BOOLEAN true
    - BOOLEAN false

That's because I (incorrectly) have *constructed* encoding, not *primitive*, which should be for universal boolean.

---

EDIT: with integer, it's even more fun https://lapo.it/asn1js/#22060101FF010100

**Comment by Adapik** [comment]
I suppose it's not an issue, really. Such behaviour is allowed by ASN.1, only BER (or more strict rules) forbid that.

**Comment by lapo-luchini** [comment]
Yep, `asn1js` doesn't validate input ASN.1, it just tries to parse it (and represent it) as well as it can; while they don't make much sense, those encoding are parsed "correctly" as far as I can say.
It would still be useful to add support for [expected constructed content](https://lapo.it/asn1js/#23090303006E5D030206C0) decoding to `content()`, but we have a (currently) failing test case for that.
