### ISSUE TITLE
ASN1 parseOctetString does not parse UTF

### ISSUE THREAD

**Issue by gserez** [lapo-luchini/asn1js#25]
My APDU response include some special UTF characters like (ş,ü,ğ), but when I try
ASN1.decode(Hex.decode("apduhexstring")).sub[0].content();
The parsed value remains string which has UTF characters.
The parseOctetString has the following snippet that only extracts ASCII characters in asn1.js file:

` if (this.isASCII(start, end))
        return stringCut(this.parseStringISO(start, end), maxLength);`

in isASCII it controls only ASCII character range
`Stream.prototype.isASCII = function (start, end) {
...
  if (c < 32 || c > 176)
            return false;
`
Can we get the UTF strings from ASN1 decoded values?

Thanks.

**Comment by lapo-luchini** [comment]
Do you have a DER to test against?

**Comment by lapo-luchini** [comment]
I generated a test vector [`0407312e3233e282ac`](https://lapo.it/asn1js/#BAcxLjIz4oKs) that could decode to UTF-8 `"1.23€"`.
