### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by HarelAshwal** [lapo-luchini/asn1js#28]
LK"I

Hi,
Great work!
Is there any plan to add this library to npm?

Harel

**Comment by lapo-luchini** [comment]
Hi, it has just been published as [@lapo/asn1js](https://www.npmjs.com/package/@lapo/asn1js).

**Comment by HarelAshwal** [comment]
LK"I

Great!,
It would of been great if you can update the readme , and add example, on how to use it with Webpack for example.

Harel
