### ISSUE TITLE
Type Of Modules OIDs JS

### ISSUE THREAD

**Issue by calum904** [lapo-luchini/asn1js#29]
Hi,

The type of keyword returns a string. The check at the bottom of oids.js does an identity check as well as an equality check. Subsequently this check is not handled appropriately and therefore segmentation faults.

The below git diff patches this problem.

Thanks.

Calum

diff --git a/oids.js b/oids.js
index bf10bf9..2eb4777 100644
--- a/oids.js
+++ b/oids.js
@@ -2318,4 +2318,4 @@ var oids = {
 "2.16.840.1.114171.500.9": { "d": "Wells Fargo EV policy", "c": "Wells Fargo WellsSecure Public Root Certificate Authority" },
 "END": ""
 };
-if (typeof module !== undefined) { module.exports = oids; }
+if (typeof module !== "undefined") { module.exports = oids; }

**Comment by lapo-luchini** [comment]
(strangely, it didn't lead to problems for me neither in browser nor NodeJS, but still an error to be fixed, thanks for the headsup)
