### ISSUE TITLE
Enumerations Not Displayed in DOM

### ISSUE THREAD

**Issue by calum904** [lapo-luchini/asn1js#30]
Hi there,

Are you able to add support for displaying the integer values for enumerations on the ASN1 tree viewer.

It is commented out at the moment but replicating what you do for integers would work nicely.
```js
    case 0x0A: // ENUMERATED
        return this.stream.parseInteger(content, content + len);
```

Thanks

Calum

**Comment by lapo-luchini** [comment]
Oh, you're right, it's a simple as that.

[ASN.1 documentation](https://www.itu.int/rec/T-REC-X.690-201508-I/en) states:
> 8.4 Encoding of an enumerated value
> The encoding of an enumerated value shall be that of the integer value with which it is associated.
