### ISSUE TITLE
Is there anyway to generate a .p7s file?

### ISSUE THREAD

**Issue by Megale** [lapo-luchini/asn1js#31]
Hi!

i already have the certificate and a a signed hash. Is there anyway i can generate a .p7s file?

Cheers

**Comment by lapo-luchini** [comment]
Hi, unfortunately not: this is a library to inspect ASN.1 data structures, not to generate them, it is read-only.

Also, in order to create a PKCS#7 signature file, not only an ASN.1 library capable of writing would be needed, but also quite a bit of cryptographic machinery.

**Comment by lapo-luchini** [comment]
(sorry, if you already have the signed hash you don't need the crypto, just an ASN.1-writing library)
