### ISSUE TITLE
Jest test runner fails because this module doesn't export commonjs

### ISSUE THREAD

**Issue by LiamDotPro** [lapo-luchini/asn1js#35]
Hello,

I'm currently using asn1js as a dependency in my React application and I'm using the built in Jest test runner. Whenever I go to to test anything to do with my certificate library I encounter an error as follows:

 ```
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import * as asn1js from "asn1js";
                                                                                                    ^

    SyntaxError: Unexpected token *
```

My understanding is if this dependency was to also serve a commonJS build then I should be able to test my code with this dependency present.

**Comment by lapo-luchini** [comment]
I don't use React myself, but usage from NodeJS or Webpack should be working, did you close the bug because it was a false alarm?
