### ISSUE TITLE
Print GeneralString

### ISSUE THREAD

**Issue by michael-o** [lapo-luchini/asn1js#39]
Please also print `GeneralString` values as you would do with `OIDs`, `BOOLEANS`, etc.

**Comment by lapo-luchini** [comment]
Do you have any example enxoded string handy?

I never really understood what [ASN.1 DER documentation](https://www.itu.int/rec/T-REC-X.690-201508-I/en) means with «All designations and invocations shall be into the smallest numbered G or C set for which there is an escape
sequence defined in the entry of the International Register of Coded Character Sets to be used with Escape Sequences.».

On the other hand, [BouncyCastle sources](https://github.com/bcgit/bc-java/blob/738dfc0132323d66ad27e7ec366666ed3e0638ab/core/src/main/java/org/bouncycastle/asn1/DERGeneralString.java) seem to treat it simply as a subset of Latin1, if I read them correctly. 🤔

**Comment by michael-o** [comment]
Yes, sure. Here is a Kerberos service ticket:
https://lapo.it/asn1js/#YIIR3QYGKwYBBQUCoIIR0TCCEc2gDTALBgkqhkiG9xIBAgKighG6BIIRtmCCEbIGCSqGSIb3EgECAgEAboIRoTCCEZ2gAwIBBaEDAgEOogcDBQAgAAAAo4IQrGGCEKgwghCkoAMCAQWhExsRQUQwMDEuU0lFTUVOUy5ORVSiMDAuoAMCAQOhJzAlGwRIVFRQGx1zaXRleC1sZGFkdy5hZDAwMS5zaWVtZW5zLm5ldKOCEFQwghBQoAMCARKhAwIBBKKCEEIEghA-AcR21xjc6DBw735zgjaiW0oVDPtb26h0BxdulYNkm1k2tYM_swgRQLjoOoEEwdWbe9VTjqx4xxoJHHJMYSKlk1UMzHZzU3ry-Bdgyy67gjW0_tjqMmkIBDXCO5zjrCrB50MMcGWIfY6rn4dgTZU1Fe-u3UNwRHhWKlB7fZmqGxG6Kcz7u3gIRoGD-HvPfhN76WYOlQFCP9mzKVdGshz3PK1-0yhIOF7EDtAE6HE2hIzaw76dUIh0gTpFO1wT3Hc1jDmLmzmurAGDAXaGFIOMW7XFUvcB4GL7SfU1KkrNCOG2_mTwNRNPz6bUqlCOycLVNvxBVeqJYzlegtxfomVwVNYQ9sygXJpjg6AnYnNFXhjlyVMvx2rRw15mi56CdoGTOefyc--96hZHDmhFRchqKE44ivZurYoixeN589rAP1Kr419WSgvsR-4VyQL3rXCGCfnAx0Ej1yv8OsHizeiTWSFZSoYm30fhxFK3jKBaYdXx4h6K75NQkKv2L-hzbM6kd4f5NIweamAIwcnqkfxeAYeOEzJ653rnvhZOAyokZvkw7XXPXsILEwIaDRwaQQ_25xvRiLRR_7MFpIKwS8kYXPIt4IHF-YkBir9hO7P8SHrzdp8FpbhKsSW-LYUGYWtg33dVokkdBCZ5rYZIW5Fz-I2yMTN57jpQ75G0_7zLPNQx8zvUYP75-tetFQZglLRE9qDXIWFMosyY1i1oafDeOTfxg8G1pT8u_CRFO02pOlbTdSwObbTechm8STu_T6Hao2UM7qRmUB2YATp9ORLYC7_g2PdAvbCTy9gKyqhojK9ToK6yD16v1iBk70xTXr93HhyS_71MhoS5AyyO7GNJ9gvFKG7u7s0Xf1bsQ8an1KdzlN-IfndoRXvjY9tO-_7r03j-EE5HSWFhMpoD2Sbj1xjUkAO2l6uGKaJ9XXqevCQZHG6aSz-lYO9R7HkrshkVCPCZqL_Nuzk4_bLkD1GdjvhmrsIRoTy7ivsixZPnvyyC9Z761Po9gqKQXPzZ8Us9WyfhQyo3k0UufhGD4wWJ0sRUwvwcMfIk988-vjN8F22uU81FFiiDZCz4nFtGHx9ZHAIh2rGdpIrPNyqtmZvPaHfASPQr2691ze4XEjSdnyGRcfZwDe4iLve-hE81a-G_AfQlyIhbT_QWPI90qVp-PP7lwyzN1aOAV7Lk6hqap5-YUaQVBReJIA8Hd9a7dRH2ZxsJSa43wktQW8yewfPRGF1f35HdKSWomoEH84vlzWlbFuQaqxdxc0NBsEjB8TlypZpZI1MYg2LUYfmCezUfL3lgV-hvfH8r3PtbAcpjRmLjn8sXhutu7LYTpZZWR0d5U_JXk35oFpTO2GFwhoPqsYtwGfRpIyN8DAZ0kLUzdOiWDKDop9KqnNj9nF6RYt86DCn5LQHwm7uYPyFw_00hoW-pnr5PsvxcxF5slYvgjQfmhGvhzI_hqI5IcfDxPiJsj7yEQiTYFZn5_3ileAIHPBkVGlySXTbNGOUivEljbN6YFH6dZhVZLfjojwnU0K3OqDRj0fWDCKAL8P6JeYOvnvD5lW-_TIwR3JHScIf7bOr6F7dZ95Wapn__mCERxyYBGaaICG07l0e4EnZtU1a40zza8epDgjHrD7XGPeLrrw8q32pE-LwnpQu8m4ifJkPX0jmw6N5fMs27DOn7yYm2r9mroXyxzg_WwRuDG7XKox2FnIbDSRCutfvISs1lvJjRPIBMmg1UZAxZo6RpbNfipiwhI6NpvNOLajh-m1PkKFz1TNLoUb5opC3zUxOsOsGS6ccv73vDMw1oVIGSEjT6s8Fxu2tLH-vjUeaB1t7NEbwcw1dhlkN8XbmvdDhJVu18Hll-Ls6OXY_dT_P1UmwkEM8O4tgrpnv1-s0dirR5ndHHZGCkscOwSzZq7_upXD10gB2jSmp8xnIrILJDqz-6zhB_jkkIY68lVpXMN8eiY609ksCu1UkURezpFt7Wq6pNmcLWCmwqqXKONJdpbh9ycpfo8tIvSBkIZo0-KH1G7h7-EtF9tmX2eaM1XdXvcR8tTnTDWk6wt674dw-1WuwOnMzdxiTrpZ4_i6jnbBHtOBz9U1yGSLumQtR-XRIcBoirKx5_MgxxZiLlr3iIrq6lRU3aDumMx2-rt5XiVmnCOBSok4dJqIreUjh5Q8y7rmYEYyBRMc5Sa1jHKuMNsTXs7FuNKe2cOHuvmYxzbUvfcRElfNdWiZvJ4u16ekYQ_SIWIii6C2acjvYEF6Ls_drxvNWQRHzSVtY7-y-XdRblPVLV9vRsqztqH1zS1WOruQOIu-bh8A1LE4Hny8xpzYBhMeLnoeQMVjfODKCcdMVWDWh8SoO9ZG8HW8Gq1wxi6MZ2b2gAevXZ4jE0lqr_BhaFOT9iZM_bDOtdX6qga-wb4A_4LWhQDn-80PUH2vFy1cCUWXANTyVqUeBiv1U0PbNSFH-GzfSFa50TAroYBzayq_X68Uxsc3-GuM1lbPysjB12zFDts1us_qOhZeioD9Zk1bDFcwV2l7WUz4ltF8pIpY5Xm4QaZDRBiCbl2mrNNVg26t4wOlbZq8HW6uxluj3JDt3m_yEqHyYKdhYFZmuT84q-mN9qQZo3reymjwrT9VFEX0_EK51oc8zquZG7WguHo3J9WhNCjSCXRB5dStfTPOkqge-ZhJtu8m28Vb-NnrCk2zVw3XD3PbUqWoxh42Hl6pCM8H95cFTws9hC3JpUbq0s2xWG-U6REAn9ZVvUS9j-pLUbjybKvakh7NU80NfoNY_PB3HCgb4dGUID8MoDO9qN6KW9wCQ_Pk0fbK3beuFlO9hHZs6v9KSIPKNISQH6dkX_CnyVEeqaF92tHiDrHJF-8VJStNuSH7ltT1_trtIpVmGtnEWmCwMSAOifAxHHi4XHQXbn-MULFN9xIX-Di4OlZ3mQsW4WjOBrLvWJq5tA5F1JkOrXM98LWmFtUxBMW2aNlWibfIaXFXmeJUPltdxcLVfDew-bzWjy0C1GlFkswJWGxabRSoa3_liAB82S9rYT1gNDdNXD7zo6gPfs4jTKa0MPgmResX0zrxJLJau8Bd9lEqcHPY3M8ciFut-2RndsmqVUiiFRqZYME0TR5CaL0BHKr7uG7E8m2vpuXyGSDC6wdVvircwUiEjxxr12RLsf2-JDXQWWwh8_CDlKrVRxWTw6jSwMLFZ99-pKuG7hKQNawz4QFG2KA-iJIqm2qdB1E4ripYs15zolr3dxvH7XaBtZbAJ6_pltuCZjvHWHtK8Yk6DRhCo2jIiLgPcreNH68SlcAeXs-LURxwlIbvqmtApdVstGzatPyYfYSU9bSYjWS9RKyO2Tli0WD2cWYKzcNZlVbkD_mSIqzbbwXt-PGrUIfRPtXf6XvzzrvJwYssavI6XQs_tTxDhsZHu7RST4APWhG07gKW8woDdpZRJ5L8nXRSXpVDRbnPRnN2hjb0pSd2xAb1gRB7ho9PkGLIcd5FpZ3r5bz3RFK2guNAvnE5pfiIWYHZ9uGAUcH1PNb39f9kf_k_tJ8XyQGX9kbLjP7pBYQDOGJLKLjgHZKi5Kg-sj5Fv93LWD5EgqewBadJkiwIXyyTFcZT5fHcRAL1cDf8xS1rxzszC59d2iaXyI8mtlOpt5is3BG9yadEPIRNIY34C4oFhqE3JxFbxxeAV_i4kxHIejWtLAQ1NuIz30UXVW-NVOxM1Gf3bA7A_tkrcw0cUpXFE0RYbtz5285uDnBZmxNVCKlZmMUFHTIepnF2H6PrncIdP5eEdpIflBGndS6TIQtoNXz_RxS1eBOtaZkywMYMB5_q9GHyF8fJnSGyU6P14ifde3IEuJSUQOigHyoAw1x0hn_XDxxa-PXzqnnkd910YGBerIPjbEymPgv-22d1LPp5M_jNH7bAPD8qONkD6jCdfyX_iwKoNJu992CYThKpjqF8Qwy1C1Wyvlj3sQG0BKxD_KxGnjzYrRHkebgdtIu00en6Q6H99gD9tpks_dGnZ9OJj-FUOP5fGooIFocd8FEuNfgLHuzUbDqFlFQEOGZ4_20yXsQl4--X0zimcaldKDAXd7O51sd8l0SAUawKR9Eqg3R6kHw-m1Rh2f7Rk_pPiCnpkh0OSpCFH8ZX2yuMr7K2Z-muxmGH5XDXGja9GojWX4xLsygLZkmO6QJwgHxcWH5KBy9zVHU4lPXHK-v3_5aDFT5UxcjgRign22J0wgBl9St6OjB4inyvXIlZI7WXlmKfRdxESCJdiGiHXwEiTwnBz3qL4NWDocjXVqd494VvurY7fhLpPZRCjZxdN7DYDrGj9X4Y0QkGwD3yRDgKPnaAiJO3q-35yc9Tofi_3-3GvToVbBI6Ia2dFrCpZxdA1fnmWwV0DztHHBNE1DK_xSh_4tmE7EYR4KEWcvatCmfs6xwLZ8qLTDkm4ec28tuAO_1iLdDiUNC3slg1Bo7TjeiEBAPfIztswmegEy9htsx-xs6jPJnf-jkOh32HY-vmUEHI7PXSI6Sixosuh-bFqcNYhd4rNXVdyGV36yxBIKkPGvtMiKb_f8Htkv7ixlWxRBpZ0hmAzinDFpzYXDdpmqx6rSgu-sllCzj98G9bfeUKlJXxV45DVTbhZnj6gH_mgkbK_NL-tZCDl5KAtLnLAeXwiVakxJQBEJy1JLwSrys-on8igdkMz9Bv9UcST8yDSrbkHbfjT_ri270j440FAmUoU_Legkaprtpd0HLQRFDfIUdswmTSryfD9I5E8oE7MyxgsVf4hz1n2rc4l0tL--ka1N2IX3l53Q4SnvH5KwYbYKHU3Eqaoq9VuyuR4Mf2lVaq02F3QE3-nlbMQBNySfOSM9swBjaokN0VXH5_5KD0UfBrfdQkBYK0cb5ZFVPzOKxbrofZXRkFGc-TiUClqLgMgmkCS8zBKm9Q1pHy10-IFchCZnDemuaHvxQY28XcY1TIatcoY_-I6pTsOG5Y6cra44GCaZKwesOyb9um4PVQCf9dUfgdOc1ImGMjS4bwzZN2jswYzKTkJuetImhSHoR2d3YyFbdhBfmpfIoo60YlOMJe2e3s_FpVCi_f5mp9JHVDONFzPuIkNA-OugpO5tqhSgZ69tv-QTD3W2huXzGQduCUx2hTMV6SJcM82R9mXVxnFfKguvYG5bGMQawcczQHkXTiIKcf12PXz1DDSgov02UAS4I4Rcn4O2rLQKQ8sC4yCtIfDQfiBsLrbsdAoTTMVC64YJH8gylFJFclVdc47Iy1jAlmL2TOEMjBQy432qso2qalZWogvkyRXPvnSVoTJ2iM14GNrXCQicnafpaF4hKgTruW4F7CV-LR0-O392boSZ1KK-L5-uz4nI67ZDDj6T6_-Ujlcp_RTczs7v88RP1AQEmUMC8CpLnEppacAUy-iKWk2jO9qivYaPgLEpCycXgDZV_DJfzRLJH3gWd2VC-Lw87ncNQ2OjuG3GIoDeqM3-YiXDdD-h_WTS4UFXcC2riQ9fq5xRBGaE-oienM-8ZjbdexPZgtQtz49MoSMElkfA1jxOfi-K4pPe0vVEKOIDyyRwpIHXMIHUoAMCARKigcwEgcmQfIUGVuxlVQqW_bFjzmMvoONR_H3Le8V4QWLUTj3wCev6iPxagu5D4OGDVphbdaHihBS77yvRFO0fc_uXexFuCAljjFTRhe3Y3CzIPPx09EKdpY9obcE2D6x2gwM0NL7vdq6JMnMP5wqgydTqybaxrTQgr5G-ZsBKbfQZvhwmWZFCBMTDJA8ciao4_ogdK05DrLZt2XeJmOPhKA_aqfc6Yx2neETxJXtvKRPsBHftF5qsrUKyKn70FnygS35BuwumNkLtgIrfkEw

**Comment by lapo-luchini** [comment]
Seems to be (a subset of?) ASCII… oh, won't hurt to enable the preview of a rarely used tag, worst can happen is it being odd or unreadable.

**Comment by michael-o** [comment]
@lapo-luchini, thanks! Looking forward for a new deployment on https://lapo.it/asn1js.

**Comment by lapo-luchini** [comment]
Already up. Hit reload. ;)

**Comment by michael-o** [comment]
Already did, works like a charm. Grazie!
