### ISSUE TITLE
Tests: UTF-8 4-byte sequence: invalid length

### ISSUE THREAD

**Issue by AbdullahMurad** [lapo-luchini/asn1js#40]
The length should be 0x0d instead of 0x0c.
https://github.com/lapo-luchini/asn1js/blob/e0dd9b8532519c532b98b037931cabfdce8d9113/test.js#L51

**Comment by lapo-luchini** [comment]
You're perfectly right. I'm adding also a final period, as comparing the partially decoded Unicode seemed to produce false positives. Now the correct length is 0x0E and using 0x0D actually gives an error.
