### ISSUE TITLE
can not run by vue

### ISSUE THREAD

**Issue by DLTech21** [lapo-luchini/asn1js#44]
while running the test code return fail

These dependencies were not found:

* int10 in ./node_modules/@lapo/asn1js/asn1.js
* oids in ./node_modules/@lapo/asn1js/asn1.js

**Comment by lapo-luchini** [comment]
Do you have a full example to reproduce the problem?

The files are sure there, as you can [check on unpkg](https://unpkg.com/browse/@lapo/asn1js@1.2.0/), or by inspecting the `node_modules` folder.

**Comment by lapo-luchini** [comment]
OK, I generated an example with `vue-cli` and I can see the problem.

**Comment by lapo-luchini** [comment]
Next commit will have this working:

```JavaScript
import ASN1 from '@lapo/asn1js';
import Hex from '@lapo/asn1js/hex';

export default {
  name: 'HelloWorld',
  props: {
    msg: String
  },
  computed: {
    exOID() {
      return ASN1.decode(Hex.decode('06032B6570')).content();
    }
  }
}
```

**Comment by lapo-luchini** [comment]
Fixed on NPM. Use this in `package.json`:
```
"dependencies": {
    "@lapo/asn1js": "^1.2.1"
}
```

**Comment by DLTech21** [comment]
thx~~~~

**Comment by NonieBenks** [comment]
@lapo-luchini hi! i have the same issue with angular

**Comment by lapo-luchini** [comment]
> @lapo-luchini hi! i have the same issue with angular

What are you building with? webpack should work, but [esbuild seems not to](https://github.com/evanw/esbuild/issues/507), at the moment.

Please open a new bug and/or provide a test example if possible.

**Comment by lapo-luchini** [comment]
> @lapo-luchini hi! i have the same issue with angular

Please try with ESM version, you can see in preview like this:
`npm install --save @lapo/asn1js@next`
Open a new issue if you have further problems.

**Comment by NonieBenks** [comment]
@lapo-luchini i just used a different lib for my project(it's done now), way more tedious than yours, but worked at the time.
was doing it with esbuild, so that was the issue
