### ISSUE TITLE
Feature Request: Darkmode

### ISSUE THREAD

**Issue by olibu** [lapo-luchini/asn1js#51]
I'm using your tool on a daily base. Many thanks for your efforts.

As most of my tools support dark mode, the asn1js page doesn't integrate well.
Thus I have create a dark mode version of your page in my fork (https://github.com/olibu/asn1js/tree/feature/darkmode)

If you like, I would send you a pull request.

I tried to keep the changes of the original files as small as possible.

**Comment by lapo-luchini** [comment]
I prefer dark pages myself lately as well so, yes, please open up a PR, thanks a lot!

PS: try to minimize the diff to make the actual changes more clear, i.e. avoid re-formatting and re-indentation. Thanks!

**Comment by olibu** [comment]
Now included in main.
Thx
