### ISSUE TITLE
Times with offset minutes parsed/printed wrong

### ISSUE THREAD

**Issue by geitda** [lapo-luchini/asn1js#54]
Times (both UTC and Generalized) with an offset that includes minutes print wrong.
`18 15 31 39 38 35 31 31 30 36 32 31 30 36 32 37 2E 33 2D 31 32 33 34` is the literal string `19851106210627.3-1234` but prints as `1985-11-06 21:06:27.3 UTC-1234:34` Those unique digits help to see what seems to be going on. My regex-fu isn't good enough to suggest a correction, but using the format that omits the offset minutes looks closer to correct: `18 13 31 39 38 35 31 31 30 36 32 31 30 36 32 37 2E 33 2D 31 32` (literal string `19851106210627.3-12`) prints `1985-11-06 21:06:27.3 UTC-12` Maybe the regex matches both hours and minutes as the hours section and then rematches the minutes as minutes? This guess is based on the code that prints this: https://github.com/lapo-luchini/asn1js/blob/b13d6cd8c835e95919f547f897e59a893d706830/asn1.js#L202-L209
This shows where the `:` is getting added.
I also noted that UTC+13:00 and UTC+14:00 (anything more that ±12:00) are treated as invalid but these do exist. I think the part `(?:[0]\d|1[0-2])` in the existing regex could be either `(?:[0]\d|1[0-4])` or `(?:[01]\d|2[0-3])` to allow these timezones to parse as OK. I don't know what ISO 8601 has to say (if anything) about a limit on the valid digits for the offset hours (minutes obviously should be 00-59). The field has a hard limit of 99 since it's only two characters wide.

**Comment by lapo-luchini** [comment]
ISO8601 and RFC3339 don't seem to refer to any timezone allowed range, but I still restricted it to `[-12,+14]` as it seems to be the [current practical limit](https://en.wikipedia.org/wiki/List_of_UTC_offsets).
