### ISSUE TITLE
lapo.it domain not renewed

### ISSUE THREAD

**Issue by dancvrcek** [lapo-luchini/asn1js#59]
Ciao Lapo,

Just noticed that your lapo.it domain registration expired. ... just in case it was not intended.

Kind regards
 Dan

**Comment by lapo-luchini** [comment]
Definitely not intended, already working on it (since 12h ago).
Hope it will be fast.

**Comment by lapo-luchini** [comment]
Solving the issue with the provider is taking a while, I created a specific domain in the meanwhile:
https://asn1js.eu/

**Comment by dancvrcek** [comment]
seems to be back up!

**Comment by dancvrcek** [comment]
Thank you, Lapo. This is the best ASN.1 parser out there - as far as I can tell.

**Comment by lapo-luchini** [comment]
> seems to be back up!

Of course it does, just right after I set up a new domain. 😂
