### ISSUE TITLE
Failed to decode a PKCS#10

### ISSUE THREAD

**Issue by lhuynh-cs** [lapo-luchini/asn1js#65]
The error message is : 
TypeError: cannot use 'in' operator to search for "optional" in "T"

The PKCS#10 is : 
`MIIBbDCB1gIBADAUMRIwEAYDVQQDEwlqc2NlcC5vcmcwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAIvoY+6r/fUTSgRPIG8ZHfzS25FP9SqiDs4hv5rlStHjSIt7kaSiK7dbhoezww/6nIZFN1IfmCAYAU6kJwIT6DtVJd1Rp01G5D2g62e4EismLIUN9LlLHFaLw402fVCAWX04DexZlO0Ub7WuEKPWves84+jWqviGg2hUQeq2pb1RAgMBAAGgGTAXBgkqhkiG9w0BCQcxChMIcGFzc3dvcmQwDQYJKoZIhvcNAQEFBQADgYEAPARlIQlioAHG+k2LUIggNy+B6kPwiEvfVsuCioKwpOFir5G2lXozZTUVCUVpgLp5KxH+L4sxFLcUsKvCyvBy27x/0LS/Me+VUV5RBVRGKfb+Zj/TiatrNTXT+IHwwesQ8lC+ZM0Z07YJMa1Tz9ogoUsdae8KGWNOPZLTBJkuU5w=`

On http://ldh.org/asn1.html, it is parsed as : 
U.P.SEQUENCE&nbsp;{
&nbsp;&nbsp;&nbsp;U.P.SEQUENCE&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;U.P.INTEGER&nbsp;0x00&nbsp;(0&nbsp;decimal)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;U.P.SEQUENCE&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;U.P.SET&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;U.P.SEQUENCE&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;U.P.OBJECTIDENTIFIER&nbsp;2.5.4.3&nbsp;(commonName)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;U.P.PrintableString&nbsp;'jscep.org'
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;U.P.SEQUENCE&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;U.P.SEQUENCE&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;U.P.OBJECTIDENTIFIER&nbsp;1.2.840.113549.1.1.1&nbsp;(RSA&nbsp;(PKCS&nbsp;#1&nbsp;v1.5)&nbsp;key&nbsp;transport&nbsp;algorithm)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;U.P.NULL&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;U.P.BITSTRING&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;00308189028181008be863eeabfdf5134a044f206f191dfcd2db914ff52aa20ece21bf9ae54ad1e3488b7b91a4a22bb75b8687b3c30ffa9c864537521f982018014ea4270213e83b5525dd51a74d46e43da0eb67b8122b262c850df4b94b1c568bc38d367d5080597d380dec5994ed146fb5ae10a3d6bdeb3ce3e8d6aaf88683685441eab6a5bd510203010001
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;U.P.SEQUENCE&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;U.P.INTEGER&nbsp;0x008be863eeabfdf5134a044f206f191dfcd2db914ff52aa20ece21bf9ae54ad1e3488b7b91a4a22bb75b8687b3c30ffa9c864537521f982018014ea4270213e83b5525dd51a74d46e43da0eb67b8122b262c850df4b94b1c568bc38d367d5080597d380dec5994ed146fb5ae10a3d6bdeb3ce3e8d6aaf88683685441eab6a5bd51
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;U.P.INTEGER&nbsp;0x010001&nbsp;(65537&nbsp;decimal)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;:&nbsp;0&nbsp;unused&nbsp;bit(s);&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[C.P.0]&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;U.P.SEQUENCE&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;U.P.OBJECTIDENTIFIER&nbsp;1.2.840.113549.1.9.7&nbsp;(Challenge&nbsp;Password&nbsp;attribute&nbsp;for&nbsp;use&nbsp;in&nbsp;signatures)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;U.P.SET&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;U.P.PrintableString&nbsp;'password'
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;U.P.SEQUENCE&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;U.P.OBJECTIDENTIFIER&nbsp;1.2.840.113549.1.1.5&nbsp;(RSA&nbsp;(PKCS&nbsp;#1&nbsp;v1.5)&nbsp;with&nbsp;SHA-1&nbsp;signature)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;U.P.NULL&nbsp;
&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;U.P.BITSTRING&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;003c0465210962a001c6fa4d8b508820372f81ea43f0884bdf56cb828a82b0a4e162af91b6957a3365351509456980ba792b11fe2f8b3114b714b0abc2caf072dbbc7fd0b4bf31ef95515e5105544629f6fe663fd389ab6b3535d3f881f0c1eb10f250be64cd19d3b60931ad53cfda20a14b1d69ef0a19634e3d92d304992e539c
3c0465210962a001c6fa4d8b508820372f81ea43f0884bdf56cb828a82b0a4e162af91b6957a3365351509456980ba792b11fe2f8b3114b714b0abc2caf072dbbc7fd0b4bf31ef95515e5105544629f6fe663fd389ab6b3535d3f881f0c1eb10f250be64cd19d3b60931ad53cfda20a14b1d69ef0a19634e3d92d304992e539c&nbsp;:&nbsp;0&nbsp;unused&nbsp;bit(s);&nbsp;
}

**Comment by lapo-luchini** [comment]
Exception should have already been fixed by ce3dc3d2bde4145203489cb67d1bebc6ca334999, can you confirm?

**Comment by lapo-luchini** [comment]
I also added parsing of main PKCS#10 type in c9324b2c17c29d7018e77bb867f02bcddb28becf.

**Comment by lhuynh-cs** [comment]
Great, thanks for the fix
