### ISSUE TITLE
Definition for CMP messages according RFC 4210

### ISSUE THREAD

**Issue by RufusJWB** [lapo-luchini/asn1js#68]
Please add a definition for CMP messages according RFC 4210. If you don't have time to do so, I'd like to help but I can't find an example where the other definitions are stored.

**Comment by lapo-luchini** [comment]
Do you have an example CMP ASN.1 to test the feature on?

I found one [as Wireshark dump](https://wiki.wireshark.org/CMP) but the link seems to be broken, no, it was [moved here](https://wiki.wireshark.org/uploads/__moin_import__/attachments/SampleCaptures/cmp_IR_sequence_OpenSSL-Cryptlib.pcap).

This is what I'm doing to add support for it:
- edit [updateRFC.sh](https://github.com/lapo-luchini/asn1js/blob/trunk/updateRFC.sh#L2) to add 4210 to downloaded RFCs
- as usual it doesn't correctly parse "as is", so I iterate parsing and [add some "patches" ](https://github.com/lapo-luchini/asn1js/blob/trunk/parseRFC.js#L6)
- `cd rfc ; ../parseRFC.js rfc4210.txt ../rfcdef.json`

In this case this is not enough, as it uses some imports and dump fails on missing `CertReqMessages FROM PKIXCRMF-2005` which should be parsed too.

I committed partial work in branch [rfc4210](https://github.com/lapo-luchini/asn1js/tree/rfc4210) (only commit d143a359a70a0ca61dd358083df2531a69ed128 right now).

**Comment by lapo-luchini** [comment]
Oh, RFC4211 was super-easy to import too and now the Wireguard example works.
Is this enough for you?

**Comment by RufusJWB** [comment]
> Oh, RFC4211 was super-easy to import too and now the Wireguard example works. Is this enough for you?

So far it looks very good, but there seems to be something not working with loading the definitions: 
<img width="829" alt="image" src="https://github.com/lapo-luchini/asn1js/assets/1633499/d857ee3a-58b5-42ac-b4df-1f36ec3b337f">

Could you investigate this? I could also provide you with a more complex CMP message.

**Comment by lapo-luchini** [comment]
Mhhh… works for me, what browser are you using?
I tested with Chrome, Edge, Firefox and Opera.
Do you have errors in console?

Did you intentionally de-activate the feature?
<img width="173" alt="image" src="https://github.com/lapo-luchini/asn1js/assets/420454/d28ccdf8-50ed-4863-aed3-d3a8b4ae6f04">

**Comment by lapo-luchini** [comment]
Oh, and feel free to attach more CMP examples.
I know little about CMP myself, so I only tested what I found around.

**Comment by RufusJWB** [comment]
> Mhhh… works for me, what browser are you using? I tested with Chrome, Edge, Firefox and Opera. Do you have errors in console?
> 
> Did you intentionally de-activate the feature? <img alt="image" width="173" src="https://user-images.githubusercontent.com/420454/269110024-d28ccdf8-50ed-4863-aed3-d3a8b4ae6f04.png">

My mistake, I found out, that I can only choose the definition after loading the example.

**Comment by RufusJWB** [comment]
Works like a charm! thank you!
