### ISSUE TITLE
`TBSCertList` definition missed `version` field

### ISSUE THREAD

**Issue by Mingun** [lapo-luchini/asn1js#72]
As you can see in this example of TR-34 Rebind Token, `TBSCertList` recognized the following fields:
- signature
- issuer
- thisUpdate

This is wrong, according to [RFC 5280](https://datatracker.ietf.org/doc/html/rfc5280#section-5.1) there is an optional `version` field which is present in the data:
![ASN 1 JavaScript decoder — Mozilla Firefox_003](https://github.com/lapo-luchini/asn1js/assets/450131/48bd5063-96f3-44b6-9231-bd97504f1ae2)

([link with example](http://lapo.it/asn1js/#MIIHmwYJKoZIhvcNAQcCoIIHjDCCB4gCAQExDTALBglghkgBZQMEAgEwggO4BgkqhkiG9w0BBwKgggOpBIIDpQIBATEAMFsGCSqGSIb3DQEHAaBOBEwwSjBBMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMVFIzNCBTYW1wbGVzMRswGQYDVQQDExJUUjM0IFNhbXBsZSBDQSBLUkQCBTQAAAAHoIIDPTCCAzkwggIhoAMCAQICBTQAAAAHMA0GCSqGSIb3DQEBCwUAMEExCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxUUjM0IFNhbXBsZXMxGzAZBgNVBAMTElRSMzQgU2FtcGxlIENBIEtESDAeFw0xMDExMDIwMDAwMDBaFw0yMDEwMjkyMzU5NTlaMEAxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxUUjM0IFNhbXBsZXMxGjAYBgNVBAMTEVRSMzQgU2FtcGxlIEtESCAyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz7zG-kJSOgA2L4QupRtR5yqbYprM_T9Vc7W4c4q3vtiCVUfVwlgLcwY7_JZTFloQ811ILdyifBIEEC4LP5gTSjkYL20EO5qhm_NTgaflCnCxGqSjM1Sl_zQ08NQcbSRVbxcrNO7b6xWtU9auNhCWTSxdQearGzVnnQJDmUFkytMd6XH-rTcMpHDeTd14Kb6GA_El5YTdsSlOk6Z7p5yS8Wz4hg180uzkMoA6FHBgeGiMpDVcYjK_IaFLEao_8CxuEHpbchZQ-8DBxgf1ZgaTuhP2YwAtENapK-qjCfZWVIj0AavYiVeHGZJXh7RaInyhNMZVy27AvGAzgxjA5GMHhwIDAQABozkwNzAJBgNVHRMEAjAAMB0GA1UdDgQWBBTPChHmS_aGUhifU_M7OVYtZMgb3TALBgNVHQ8EBAMCBsAwDQYJKoZIhvcNAQELBQADggEBAAW8mlCqpYUDgUHMQ16vE3jL0XrJpbFPve-Rp6smiDvrF9xO6cFfd2B9UOc3FnoR4UkiZvRMbK0CyE0QSZGLQI5Po_jn_Y2P4Yxhzmt3ChjxUY1446cWXpRVML0Ab3eWp4Z3dDrPeBp2ipw2RLy2r_BiQqSM9wtPjv77MFWOZp0MJjHEHxebW78o_XUD25Pmdd05wCpuYfrkhnh_Oxl6C088iOik-AzUjL2IYGhH2iNhbx0KuekJ8JFrN4TsLixetD3dJeuP1AscWeIbGMqwnjw1lQpvfK0nsYOVjOg5-8qz960nbLHipaWLXNgNh80agowwYpHo1oDHGBTZpbhRbrgxAKGCAdgwggHUMIG9AgEBMA0GCSqGSIb3DQEBCwUAMEExCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxUUjM0IFNhbXBsZXMxGzAZBgNVBAMTElRSMzQgU2FtcGxlIENBIEtESBcNMTAxMTAyMTczMzMwWhcNMTAxMjAyMTczMzMwWjBIMBYCBTQAAAAIFw0xMDExMDIxNzI4MTNaMBYCBTQAAAAKFw0xMDExMDIxNzMxNDZaMBYCBTQAAAALFw0xMDExMDIxNzMzMjVaMA0GCSqGSIb3DQEBCwUAA4IBAQA28Go8iKy8-p-OOwhQ7uCanPe1spGIblENNJ_l8Fwb232fOeTqZQiCjy7T7nljyFh0UnlcOUYrBg1blyyae174kKGTxXIl0ciNVu7R0D9-mnWHDWBNFeAS_9e4UG6kuhTntRAYwW2NnvtqxcUVaGsTThax1n8ei_Q8j8mmC5YUrczpr2nCepRT1CY0T2sURQ7lg4IUdB6r9_h_FSqTGfrZ7TtIGhE8AzY9Ka3QLjAxOik6_Bh7clKY-xTF2ZeWeFomzBnPB8K8miO49vbuGaAHkE9L9jLc_efygl8xL-Yo49DHHNULsI7kBOKl8BGgtatPKmEnXiUAna4AZg7_MtbDMYIB2jCCAdYCAQEwSjBBMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMVFIzNCBTYW1wbGVzMRswGQYDVQQDExJUUjM0IFNhbXBsZSBDQSBLREgCBTQAAAAGMAsGCWCGSAFlAwQCAaBlMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwIwGAYKKoZIhvcNAQkZAzEKBAh96hwAiU4kajAvBgkqhkiG9w0BCQQxIgQgkXNPx0ECAEMGFZbZYfEoELvzjygui4qKEgHsFDh9CZAwDQYJKoZIhvcNAQEBBQAEggEAnyPN7KJfU-Ypw62vyJb-bsaJhAepyh42fPBOKgql0Awg3SD0DyS98c-kVwobnSMcGWnBwfMlCWtmc3lc8yprCIacnma5BnJQfOdXNVfumO3k2JQ6qO2XWldRTY44Cxao3tAdbqG8hxBFwE1yT_PXkp1pyi00JZD_JwSW1PU4WSQjVw3yNcGeWpdJWk_jy_KFoSN9T2SmD_h4OzdqMSlOy7nAWhciARRoYbuWoCpjTVAAsVrb2IE8qomhRdOqOOo-RSKcpj--mP3oy0o1THJxmwbW1pKbRs6A4gPqlJAbJDcnkj3rkyx8mywC1OJn_3W36g1Y8HB3RhqxljPs2aot_w))

**Comment by lapo-luchini** [comment]
Commit 6f4b911c4f1477e8fd7d3625edd257cbceba0e97 in branch `esm` has fixed this.

**Comment by lapo-luchini** [comment]
@Mingun do you know the licensing status of that example?
Does it allow re-publishing?
(in that case, I'd consider committing it to the "examples" folder of the project)

**Comment by Mingun** [comment]
If you need some formal licensing clause just say what licence you prefer. Or I can made a PR with the example myself, just say me how it should look

**Comment by lapo-luchini** [comment]
The project uses the ISC license (basically a simpified BSD2), if you agree with that and create a PR that'd be perfect!
You can see 826f20ce2e05e13d18ef046cbcb10f6607783dc1 which is a recent commit where I added an example file.
