### ISSUE TITLE
Possible incorrect type inferring

### ISSUE THREAD

**Issue by RufusJWB** [lapo-luchini/asn1js#78]
While decoding CMP messages (it can be reproduced with the CMP example) I noticed, that the type inferring for CHOICEs might be wrong:

![image](https://github.com/lapo-luchini/asn1js/assets/1633499/bbc0ac9a-c04e-4def-ad12-2945bfe5f84f)

In my understanding, the SENDER field should have an inner field of type "Name" and not "AnotherName".

**Comment by RufusJWB** [comment]
Actually the recipient field is also incorrect.

**Comment by olibu** [comment]
Can you provide the show example?

**Comment by RufusJWB** [comment]
> Can you provide the show example?

It's already here:

![image](https://github.com/lapo-luchini/asn1js/assets/1633499/de375e47-3c33-49b6-b10d-31351461fa2d)

**Comment by lapo-luchini** [comment]
I improved recognition and now it shows the correct choice.
Thanks for noticing this!

**Comment by RufusJWB** [comment]
thank you for fixing! Your little tool truly makes life easier for us poor people working directly with DER encoded data structures. I'd love to see it integrated into the debugger window of Visual Studio Code as formatter...
