### ISSUE TITLE
Button to copy textual representation to clipboard

### ISSUE THREAD

**Issue by ralienpp** [lapo-luchini/asn1js#83]
I think it would be beneficial to add a feature to the context-menu of a node (at least the root), to copy it and its children to the clipboard.

My use case is to visualize two structures, copy the text from both to something like Meld or WinMerge and then see the delta between them. I can still do it in the current version, for which I am very grateful; the proposed feature would save a few clicks and remove the need to scroll when dealing with large structures.

**Comment by olibu** [comment]
There is a pull request for a feature like this (https://github.com/lapo-luchini/asn1js/pull/82).
You can try it from my page at https://olibu.github.io/asn1js/ . Just click on the part in the hex view to copy it.

**Comment by lapo-luchini** [comment]
I'm also considering a native #61 diff mode, but I'm not sure when that will happen.

**Comment by lapo-luchini** [comment]
> try it from my page

Now available from official website too.

**Comment by ralienpp** [comment]
Thank you both for your effort, this feature makes me very happy!
