### ISSUE TITLE
Certificate Revocation List

### ISSUE THREAD

**Issue by ricardo-reis-1970** [lapo-luchini/asn1js#93]
Dear Lapo,

I've been using this website extensively for checking a wide array of digital certificates. One thing I find missing is that I don't find a definition for **X.509 CRL**s. My options when checking a CRL are either (1) open it as something else (an x.509 Certificate, typically) and then deal with all the wrong encoding interpretation, or (2) open it with `no definition`, in which case I'm down to DER encoding.

If I knew where the definitions are, I would be offering to have a shot at this, but I poked around this repo and I could not locate them.

Is this something that could be added?

**Comment by lapo-luchini** [comment]
Oh, nice catch. The CRL definition was already parsed from RFC 5280 and it was as simple as adding it to the list of common objects: a7276bfdd151c1e25f4763648d202d8d92e6a3c2.
