### ISSUE TITLE
asn1.js requires to be built

### ISSUE THREAD

**Issue by allenhwkim** [lapo-luchini/asn1js#95]
It requires local files './int10' and './oids'.
This works well when you run these file with local .mjs. or with webpack-kind of build tool.

However, when it is built with AWS lambda, `sam build`, these files are not included in build output.
This cause an error

![image](https://github.com/user-attachments/assets/dd78884b-c47b-4e5b-9963-897a0567af46)

A simple build tool can do this job to make a single file without local file dependency.
I also checked all other files as well, but all other files does not file local file depencency except `asn1.js`

**Comment by lapo-luchini** [comment]
The filename in your error suggests usage of [old 1.2.4 release](https://github.com/lapo-luchini/asn1js/blob/1.2.4/asn1.js#L22):
```js
var Int10 = require('./int10');
```
Ha you tried a [more recent version](https://github.com/lapo-luchini/asn1js/blob/2.0.4/asn1.js#L16), which is ESM-based and compatible with all the building tools I tried? (I didn't try AWS `sam`, though)
```js
import { Int10 } from './int10.js';
```

**Comment by lapo-luchini** [comment]
Yes, I tried it using Docker and it works fine.

[test-aws-sam.zip](https://github.com/user-attachments/files/17531332/test-aws-sam.zip)

```
% docker build . -t mylambda:latest
% docker run -p 8080:8080 -t mylambda:latest
% curl -XPOST "http://localhost:8080/2015-03-31/functions/function/invocations" -d '{}'
{"statusCode":200,"body":"1.3.101.112\ncurveEd25519\nEdDSA 25519 signature algorithm"}
```
